set_property IOSTANDARD LVCMOS33 [get_ports cs]
set_property IOSTANDARD LVCMOS33 [get_ports rd]
set_property IOSTANDARD LVCMOS33 [get_ports rs]
set_property IOSTANDARD LVCMOS33 [get_ports rstn]
set_property IOSTANDARD LVCMOS33 [get_ports rx]
set_property IOSTANDARD LVCMOS33 [get_ports wr]
set_property PACKAGE_PIN L20 [get_ports cs]
set_property PACKAGE_PIN G19 [get_ports rd]
set_property PACKAGE_PIN M18 [get_ports rs]
set_property PACKAGE_PIN D18 [get_ports rstn]
set_property PACKAGE_PIN A20 [get_ports rx]
set_property PACKAGE_PIN L19 [get_ports wr]
set_property PACKAGE_PIN E18 [get_ports {dout[7]}]
set_property PACKAGE_PIN F17 [get_ports {dout[2]}]
set_property PACKAGE_PIN M17 [get_ports {dout[1]}]
set_property PACKAGE_PIN M20 [get_ports {dout[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sample}]


#set_property -dict { PACKAGE_PIN R2    IOSTANDARD SSTL135 } [get_ports { pclk }]; #IO_L12P_T1_MRCC_34 Sch=ddr3_clk[200]
#create_clock -add -name sys_clk_pin -period 10.000 -waveform {0 5.000}  [get_ports { pclk }];

set_property IOSTANDARD LVCMOS33 [get_ports tx]


set_property PACKAGE_PIN B19 [get_ports B2]
set_property IOSTANDARD LVCMOS33 [get_ports B2]
set_property PACKAGE_PIN E17 [get_ports B1]
set_property IOSTANDARD LVCMOS33 [get_ports B1]
set_property PACKAGE_PIN D19 [get_ports pwm]
set_property IOSTANDARD LVCMOS33 [get_ports pwm]
set_property PACKAGE_PIN F16 [get_ports {dout[5]}]
set_property PACKAGE_PIN E19 [get_ports {dout[4]}]
set_property PACKAGE_PIN D20 [get_ports {dout[6]}]
set_property PACKAGE_PIN K14 [get_ports tx]
set_property PACKAGE_PIN M19 [get_ports {dout[3]}]
set_property PACKAGE_PIN J14 [get_ports sample]
